import { StyleSheet } from "react-native";
import { colors } from "../constants";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F0FDFF',
  },
  scrollContent: {
    paddingBottom: 30,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 30,
    backgroundColor: '#008B8B',
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: '#20B2AA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#FFFFFF',
    textAlign: 'center',
    opacity: 0.95,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 1,
  },
  card: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 15,
    padding: 20,
    shadowColor: '#20B2AA',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#20B2AA',
    marginBottom: 15,
  },
  dropdown: {
    borderWidth: 2,
    borderColor: '#B0E0E6',
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 16,
    backgroundColor: '#FAFFFE',
  },
  dropdownContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownText: {
    fontSize: 16,
    color: '#708090',
  },
  dropdownTextSelected: {
    color: '#20B2AA',
    fontWeight: '500',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#20B2AA',
  },
  selectedInfo: {
    backgroundColor: '#F0FDFF',
    borderRadius: 10,
    padding: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#20B2AA',
  },
  selectedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  selectedLabel: {
    fontSize: 16,
    color: '#708090',
    fontWeight: '500',
  },
  selectedValue: {
    fontSize: 16,
    color: '#20B2AA',
    fontWeight: '600',
  },
  instructionBox: {
    backgroundColor: '#F0FDFF',
    borderRadius: 10,
    padding: 15,
    borderWidth: 1,
    borderColor: '#B0E0E6',
    borderStyle: 'dashed',
  },
  instructionText: {
    fontSize: 16,
    color: '#708090',
    textAlign: 'center',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 25,
    paddingBottom: 15,
  },
  calendarTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#20B2AA',
  },
  todayButton: {
    backgroundColor: '#20B2AA',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowColor: '#20B2AA',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  todayButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  calendarContainer: {
    marginHorizontal: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#20B2AA',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    paddingVertical: 10,
  },
  calendarStrip: {
    height: 120,
    paddingTop: 10,
    paddingBottom: 10,
  },
  calendarHeaderStyle: {
    color: '#20B2AA',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 10,
  },
  dateNumberStyle: {
    color: '#708090',
    fontSize: 16,
    fontWeight: '500',
  },
  dayNameStyle: {
    color: '#708090',
    fontSize: 12,
    fontWeight: '500',
  },
  highlightDateNumberStyle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  highlightDateNameStyle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  disabledDateNameStyle: {
    color: '#CCCCCC',
    fontSize: 12,
  },
  disabledDateNumberStyle: {
    color: '#CCCCCC',
    fontSize: 16,
  },
  submitButton: {
    backgroundColor: '#20B2AA',
    marginHorizontal: 20,
    marginTop: 30,
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: '#20B2AA',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  submitButtonDisabled: {
    backgroundColor: '#B0E0E6',
    shadowOpacity: 0.1,
    elevation: 2,
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    maxHeight: '80%',
    minHeight: '50%',
  },
  modalHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E0F8F8',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#20B2AA',
    marginBottom: 5,
  },
  modalSubtitle: {
    fontSize: 16,
    color: '#708090',
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  modalFooter: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E0F8F8',
  },
  modalButton: {
    backgroundColor: '#20B2AA',
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
});


export default styles;