import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: '#fff' },
  title: { fontSize: 24, fontWeight: 'bold', marginBottom: 16, alignSelf: 'center' },
  questionBox: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 12, marginBottom: 16 },
  label: { fontSize: 16, marginBottom: 4, textAlign: 'left' },
  typeRow: { flexDirection: 'row', justifyContent: 'flex-start', marginBottom: 8 },
  typeButton: { padding: 8, marginRight: 8, borderWidth: 1, borderColor: '#aaa', borderRadius: 6 },
  typeButtonSelected: { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  typeText: { color: '#333' },
  typeTextSelected: { color: '#fff', fontWeight: 'bold' },
  input: { borderWidth: 1, borderColor: '#ccc', borderRadius: 6, padding: 8, marginBottom: 8, textAlign: 'left' },
  addOptionBtn: { alignSelf: 'flex-start', marginTop: 4 },
  addOptionText: { color: '#007AFF', fontWeight: 'bold' },
  addBtn: {
    backgroundColor: '#28a745',
    borderRadius: 8,
    alignItems: 'center',
    flex: 1,
    height: 54,
    justifyContent: 'center',
  },
  addBtnText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  saveBtn: { backgroundColor: '#007AFF', padding: 10, borderRadius: 6, alignItems: 'center', marginTop: 8 },
  saveBtnText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  deleteIconBtn: { padding: 4, marginLeft: 8, marginTop: 2, alignSelf: 'flex-end' },
  editIconBtn: { padding: 4, marginLeft: 4, marginTop: 2, alignSelf: 'flex-end' },
  savedBox: { backgroundColor: '#f0f8ff', borderRadius: 8, padding: 10, marginTop: 8 },
  savedTitle: { fontWeight: 'bold', fontSize: 16, marginBottom: 4, textAlign: 'left' },
  savedText: { fontSize: 16, marginBottom: 4, textAlign: 'left' },
  savedOption: { fontSize: 15, marginLeft: 8, marginTop: 2, textAlign: 'left' },
  saveQuestionnaireBtn: {
    backgroundColor: '#0056b3',
    borderRadius: 8,
    alignItems: 'center',
    flex: 1,
    height: 54,
    justifyContent: 'center',
  },
  saveQuestionnaireText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  optionDeleteIconBtn: { padding: 4, marginLeft: 4 },
  bottomButtonsContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#fff',
    padding: 12,
    borderTopWidth: 1,
    borderColor: '#eee',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    minHeight: 54,
  },
});
export default styles;